document.write("<a name=\"fdiso\"></a>\n")
document.write("<h2><font color=\"#df8f06\">ISO image floppy set</font></h2>\n")
document.write("\n")
document.write("<form method=\"post\" action=\"http://mirror.slitaz.org/floppies/download.php\">\n")
document.write("<p>\n")
document.write("You may need these images to\n")
document.write("<a href=\"http://doc.slitaz.org/en:guides:uncommoninst#floppy-install\">\n")
document.write("install SliTaz</a>\n")
document.write("<select name=\"iso\">\n")
document.write("	<option value=\"iso/cooking/slitaz-cooking.iso\">core cooking</option>\n")
document.write("	<option value=\"iso/cooking/flavors/slitaz-cooking-base.iso\">base cooking</option>\n")
document.write("	<option value=\"iso/cooking/flavors/slitaz-cooking-loram.iso\">loram cooking</option>\n")
document.write("	<option value=\"iso/3.0/slitaz-3.0.iso\" selected=\"selected\">core 3.0</option>\n")
document.write("	<option value=\"iso/3.0/flavors/slitaz-3.0-base.iso\">base 3.0</option>\n")
document.write("	<option value=\"iso/3.0/flavors/slitaz-3.0-loram.iso\">loram 3.0</option>\n")
document.write("	<option value=\"iso/2.0/slitaz-2.0.iso\">core 2.0</option>\n")
document.write("	<option value=\"iso/2.0/flavors/slitaz-2.0-base.iso\">base 2.0</option>\n")
document.write("	<option value=\"iso/2.0/flavors/slitaz-loram.iso\">loram 2.0</option>\n")
document.write("	<option value=\"iso/1.0/slitaz-1.0.iso\">core 1.0</option>\n")
document.write("</select>\n")
document.write("<input name=\"build\" value=\"Build floppy set\" type=\"submit\" />\n")
document.write("</p>\n")
document.write("</form>\n")
document.write("<p>\n")
document.write("You can restore the ISO image on your hard disk using :\n")
document.write("</p>\n")
document.write("<pre>\n")
document.write("# dd if=/dev/fd0 of=fdiso01.img\n")
document.write("# dd if=/dev/fd0 of=fdiso02.img\n")
document.write("# ...\n")
document.write("# cat fdiso*.img | cpio -i\n")
document.write("</pre>\n")
