document.write("<!-- Header -->\n")
document.write("<div id=\"header\">\n")
document.write("    <a name=\"top\"></a>\n")
document.write("<!-- Access -->\n")
document.write("<div id=\"access\">\n")
document.write("	<a href=\"floppy-grub4dos\" title=\"Boot tools\">Generic boot floppy</a> |\n")
document.write("	<a href=\"http://tiny.slitaz.org/\" title=\"SliTaz for (very) old PC\">Tiny SliTaz</a> |\n")
document.write("	<a href=\"index-loram.html\" title=\"Floppy image sets for low ram systems\">Loram floppies</a> |\n")
document.write("	<a href=\"builder/index.php\" title=\"Build floppies with your own kernel and initramfs\">Floppy set web builder</a> |\n")
document.write("	<a href=\"builder/bootloader\" title=\"Build your floppy sets without Internet\">Shell builder</a>\n")
document.write("</div>   \n")
document.write("	<a href=\"http://www.slitaz.org/\"><img id=\"logo\" \n")
document.write("	   src=\"../css/pics/website/logo.png\" title=\"www.slitaz.org\" \n")
document.write("	   alt=\"www.slitaz.org\" \n")
document.write("	   style=\"border: 0px solid ; width: 200px; height: 74px;\" /></a>\n")
document.write("	<p id=\"titre\">#!/boot/floppies</p>\n")
document.write("</div>\n")
document.write("\n")
document.write("<!-- Navigation menu -->\n")
document.write("<div id=\"nav\">\n")
document.write("\n")
