document.write("<div class=\"nav_box\">\n")
document.write("<h4>Available boot floppies</h4>\n")
document.write("<ul>\n")
document.write("	<li><a href=\"index-3.0.html\">SliTaz 3.0</a></li>\n")
document.write("	<li><a href=\"index-loram-3.0.html\">SliTaz loram 3.0</a></li>\n")
document.write("	<li><a href=\"index-2.0.html\">SliTaz 2.0</a></li>\n")
document.write("	<li><a href=\"index-1.0.html\">SliTaz 1.0</a></li>\n")
document.write("</ul>\n")
document.write("</div>\n")
document.write("\n")
document.write("<div class=\"nav_box\">\n")
document.write("<h4>Images generation</h4>\n")
document.write("<p>\n")
document.write("All these floppy images are built with <b>bootfloppybox</b> from\n")
document.write("a <i>core</i> or a <i>3in1</i> iso. The <i>loram</i> is preprocessed by\n")
document.write("<b>tazlitobox</b> (Low RAM tab). These tools are available since 3.0.\n")
document.write("</p>\n")
document.write("</div>\n")
document.write("\n")
document.write("<!-- End navigation menu -->\n")
document.write("</div>\n")
document.write("\n")
document.write("<!-- Content top. -->\n")
document.write("<div id=\"content_top\">\n")
document.write("<div class=\"top_left\"></div>\n")
document.write("<div class=\"top_right\"></div>\n")
document.write("</div>\n")
document.write("\n")
document.write("<!-- Content -->\n")
document.write("<div id=\"content\">\n")
document.write("\n")
document.write("<h1><font color=\"#3e1220\">Boot</font></h1>\n")
document.write("<h2><font color=\"#df8f06\">Floppy image set</font></h2>\n")
document.write("\n")
document.write("<p>\n")
document.write("This floppy set will boot a Slitaz stable version. You can write floppies\n")
document.write("with SliTaz <i>bootfloppybox</i>, \n")
document.write("<a href=\"http://en.wikipedia.org/wiki/RaWrite\">Windows rawrite</a> or simply dd:\n")
document.write("</p><pre># dd if=fd001.img of=/dev/fd0\n")
document.write("</pre>\n")
document.write("\n")
document.write("<p>\n")
document.write("If you have a CD-ROM, an USB port and an USB key or a network card, but you\n")
document.write("can't boot these devices directly, then try\n")
document.write("<a href=\"http://mirror.slitaz.org/boot/floppy-grub4dos\">floppy-grub4dos</a> \n")
document.write("first. This 1.44Mb floppy provides tiny programs to boot these devices without BIOS\n")
document.write("support and some other tools.\n")
document.write("</p>\n")
