#!/bin/sh
#
# TazU - SliTaz Users account utility
#
# This tool is used to mange SliTaz users accounts on bugs.slitaz.org
# and scn.slitaz.org. It can also be used to admin TinyCM users DB.
#
# Copyright 2016 (C) SliTaz GNU/Linux - BSD License
# Author: Christophe Lincoln <pankso@slitaz.org>
#
. /lib/libtaz.sh
check_root

authfile="/var/lib/slitaz/auth/people"
people="/var/lib/slitaz/people"
user="$1"

#
# Functions
#

usage() {
	cat << EOT

Usage: $(basename $0) [user|command] [--option]

Commands:
  count    Count all users
  list     List all users
  check    Check accounts integrity

Options:
  --admin  Make user admin
  --edit   Edit user account.conf
  --del    Delete a user account

EOT
}

no_account() {
	echo "No user account for: $user"
}

deluser() {
	if [ -d "${people}/${user}" ]; then
		rm -rf "${people}/${user}"
	fi
	sed -i "/^${user}:/"d $authfile
}

#
# Commands
#

case "$1" in
	"") usage ;;
	count)
		echo -n "Users: "
		colorize 34 "$(ls $people | wc -l)" ;;
	list)
		# List all users
		newline
		boldify "SliTaz users list"
		separator
		for user in $(ls $people)
		do
			if ! [ -f "$people/$user/account.conf" ]; then
				echo -n "$(colorize 31 "$user")"
				echo -e "\\033[16GCORRUPTED" && continue
			fi
			. $people/$user/account.conf
			echo -n "$(colorize 34 "$user")"
			echo -e "\\033[16G${NAME}"
		done 
		separator && newline ;;
	check)
		# Check accounts and auth file
		newline
		boldify "SliTaz accounts integrity"
		separator
		echo "$(colorize 33 "Checking account.conf files...")"
		for user in $(ls $people)
		do
			if ! [ -f "$people/$user/account.conf" ]; then
				echo -n "$(colorize 30 "$user")"
				echo -e "\\033[16GMissing account.conf"
			else # check empty VALUES
				. "$people/$user/account.conf"
				if [ -z "$NAME" ]; then
					echo -n "$(colorize 30 "$user")"
					echo -e "\\033[16GMissing NAME"
				fi
				if [ -z "$MAIL" ]; then
					echo -n "$(colorize 30 "$user")"
					echo -e "\\033[16GMissing MAIL"
				fi
				if [ -z "$KEY" ]; then
					echo -n "$(colorize 30 "$user")"
					echo -e "\\033[16GMissing KEY"
				fi
				unset NAME MAIL KEY
			fi
		done
		echo "$(colorize 33 "Checking auth file...")"
		for user in $(cat $authfile | cut -d : -f 1)
		do
			if ! [ -d "$people/$user" ]; then
				echo -n "$(colorize 30 "$user")"
				echo -e "\\033[16GMissing in DB"
			fi
		done
		separator 
		echo "Use 'tazu user --del' to remove a corrupted account" && newline ;;
	*)
		# Handle general: --options
		case " $@ " in
			*\ --admin\ *)
				# Admin user
				if fgrep -q ADMIN_USER= ${people}/${user}/account.conf; then
					echo -n "User is already admin: " && colorize 34 "$user" 
				else
					echo -n "Adding $user to admin users..."
					echo 'ADMIN_USER="yes"' >> ${people}/${user}/account.conf
					status
				fi ;;
			
			*\ --edit\ *)
				# Edit a user account
				if [ -f "${people}/${user}/account.conf" ]; then 
					nano ${people}/${user}/account.conf
				else
					no_account
				fi ;;
			
			*\ --del\ *)
				# Delete a user
				if [ -d "${people}/${user}" ]; then
					echo -n "Deleting user: $(colorize 34 "$user")" 
					deluser && status
				else
					no_account
				fi ;;
			
			*)
				# Show user info
				if [ -d "${people}/${user}" ]; then	
					newline
					echo "$(boldify "User:") $(colorize 34 "$user")"
					separator
					cat $people/$user/account.conf | grep "="
					separator && newline
				else
					no_account
				fi ;;
		esac ;;
esac

exit 0
